[project]
name = 'Decentralized-Community-Solar-Project-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credit-distribution]
path = 'contracts/credit-distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-production-tracking]
path = 'contracts/energy-production-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-fund]
path = 'contracts/maintenance-fund.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
